config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root to: 'categories#index'
  
  post '/search', to: 'products#index'

#  devise_scope :user do
#   get '/users/sign_out', to:'devise/sessions#destroy'
#  end

#  ActiveAdmin.routes(self)

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
 
  resources :categories, only: [:index] do
    resources :products, only: [:index]
  end

  resources :order_items, path: 'cart/items'
  resources :static

  get '/cart', to: 'order_items#index'
  
  get '/cart/checkout', to: 'orders#new', as: :checkout
  
  patch '/cart/checkout', to: 'orders#create'
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/active_admin_adapter.rb
class ActiveAdminAdapter < ActiveAdmin::AuthorizationAdapter

  def authorized?(action, subject = nil)
    user.try(:admin?)
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord

  has_many :product_categories
  has_many :products, through: :product_categories
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :items, class_name: 'OrderItem', dependent: :destroy
  belongs_to :user
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :product
end

app/models/product.rb
class Product < ApplicationRecord
  validates :title, presence: true

  has_many :product_categories
  has_many :categories, through: :product_categories
  has_many :variants, class_name: 'ProductVariant'

  searchkick word_middle: [:title, :description]
end

app/models/product_category.rb
class ProductCategory < ApplicationRecord
  belongs_to :product
  belongs_to :category
end

app/models/product_variant.rb
class ProductVariant < ApplicationRecord
  belongs_to :product
end

app/models/shopping_cart.rb
class ShoppingCart

  delegate :sub_total, to: :order

  def initialize(token:)
    @token = token
  end

  def order
    @order ||= Order.find_or_create_by(user: @token, status: 'cart') do |order|
      order.sub_total = 0
    end
  end

  def items_count
    order.items.sum(:quantity)
  end

  def add_item(product_id:, quantity: 1)
    product = Product.find(product_id)
    
    order_item = order.items.find_or_initialize_by(
      product_id: product_id
    )

    order_item.price = product.price
    order_item.quantity = quantity

    ActiveRecord::Base.transaction do
      order_item.save
      update_sub_total!
    end
  end

  def remove_item(id:)
    ActiveRecord::Base.transaction do
      order.items.destroy(id)
      update_sub_total!
    end
  end

  private
  def update_sub_total!
    order.sub_total = order.items.sum('quantity*price')
    order.save
  end

end

app/models/user.rb
class User < ApplicationRecord
  
  has_many :orders, dependent: :destroy

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: [:google_oauth2]
  
  def self.from_google(email:, full_name:, uid:, avatar_url:)
    create_with(uid: uid, full_name: full_name, avatar_url: avatar_url, password: Devise.friendly_token[0,20]).find_or_create_by!(email: email)
  end

end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.joins(:products).select('categories.*, count(products.id) as products_count').group('categories.id').order(:title).page params[:page]
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  
  before_action :authenticate_user!

  def new
    @order = current_cart.order
  end

  def create
    @order = current_cart.order

    if @order.update_attributes(order_params.merge(status: 'open'))
      redirect_to root_path
    else
      render :new
    end
  end

  private

  def order_params

    params.require(:order).permit(:first_name, :last_name)

  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  
  def index
    search = params[:search].present? ? params[:search] :nil
    if search 
      @products = Product.search(search).results
    else 
      @category = Category.find(params[:category_id])
      @products = @category.products.includes(:variants).order(:title)
    end
  end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def index
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/views/categories/index.html.erb
<%= form_tag search_path do %>

  <p>
    <%= text_field_tag :search %>
    <%= submit_tag "Search"%>
  </p>

<% end %>

<h2>Categories </h2>

<ol>

  <% @categories.each do |category| %>
    <li>
      <%= link_to category_products_path(category) do %>
        <%= category.title %>
        (<%= category.products_count %> products)
      <%end%>
    </li>
  <% end %>

</ol>
<%= paginate @categories %>

app/views/orders/new.html.erb
<h2>Checkout</h2>

<%= form_for @order, url: checkout_path do |f| %>

  <div class="form-group">
    <%= f.label :first_name %>
    <%= f.text_field :first_name %>
  </div>

  <div class="form-group">
    <%= f.label :last_name %>
    <%= f.text_field :last_name %>
  </div>

  <%= f.submit 'Checkout' %>

<% end %>

app/views/products/index.html.erb
<h2>
  <%= link_to "Categories", root_path %>
  <%= @category ? @category.title : nil %>
  Products
</h2>

<ol>

  <% @products.each do |product| %>
  
    <li>
  
      <%= product.title%> (<%= number_to_currency product.price %>)
        
        <%= form_tag order_items_path do %>
          <%= hidden_field_tag :product_id, product.id %>
          <%= number_field_tag :quantity, 1 %>
          <%= submit_tag "Add to Cart" %>
        <% end %>
      
      <ul>
      
        <% product.variants.each do |variant| %>
      
          <li>
            <%= variant.title%> (<%= number_to_currency variant.price %>)
          </li>
      
        <% end %>
      
      </ul>
    
    </li>
  
  <% end %>

</ol>